import { makeStyles } from "@mui/styles";

export default makeStyles((theme) => ({
  firstCard: {
    position: "absolute",
    width: "188px",
    height: "218px",
    left: "100px",
    top: "0px",
    border:"1px solid red"
  },
  Pic: {
    position: "absolute",
    width: "42px",
    height: "42px",
    left: "289px",
    top: "0px",
  },
  SecondCard: {
    position: "absolute",
    width: "52%",
    height: "339.31px",
    left: "47.665px",
    border: "1px solid",
    top: "230px",
    background: "#FFFFFF",
    boxShadow: "0px 40px 70px -18px rgba(0, 0, 0, 0.1)",
    borderRadius: "8px",
  },
  ThirdCard: {
    position: "absolute",
    width: "55%",
    height: "290.98px",
    left: "376px",
    top: "20px",
    background: "#FFFFFF",
    border: "1px solid",
    boxShadow: "0px 28px 60px -12px rgba(0, 0, 0, 0.05)",
    borderRadius: "8px",
  },
  FourthCard: {
    position: "absolute",
    width: "70%",
    height: "113px",
    left: "386px",
    top: "320px",
    border: "1px solid",
    background: "#FFFFFF",
    boxSizing: "border-box",
    borderRadius: "8px",
    padding: "20px",
  },
  FourthCardBox: {
    backgroundColor: "#F3F5FA",
    borderRadius: "6px",
  },
  Text14k: {
    fontSize: "40px",
    fontWeight: 600,
    fontFamily: "Inter",
    padding: "5px",
    textAlign: "center",
  },
  Follower: {
    fontWeight: 500,
    fontSize: "16px",
    fontFamily: "Inter",
    color: "#8A8E97",
  },
  FifthCard: {
    position: "absolute",
    width: "40%",
    height: "76px",
    left: "386px",
    top: "440px",
    border: "1px solid",
    background: "#FFFFFF",
    boxShadow: "0px 35px 80px -14px rgba(0, 0, 0, 0.08)",
    borderRadius: "8px",
    display: "flex",
  },
}));
